INSERT INTO USUARIOS_WEB (CHAVE, CODIGO_BASE, CPF, SENHA) VALUES (USUARIOS_WEB_SEQ.NEXTVAL, 100010, 'CPF', 'SENHA')

SELECT * FROM USUARIOS_WEB

SELECT CHAVE, CODIGO_BASE, CPF FROM USUARIOS_WEB WHERE CPF = '27567962802' AND SENHA = 'MTUwMTk5'

DELETE FROM USUARIOS_WEB

SELECT * FROM TIPO_CARGO_WEB ORDER BY CHAVE

SELECT CHAVE, CODIGO||' - '||DESCRICAO CARGO FROM TIPO_CARGO_WEB WHERE CODIGO_BASE = 100010

SELECT * FROM TALENTOS_WEB

DELETE FROM TALENTOS_WEB

INSERT INTO TALENTOS_WEB (
  CHAVE, CODIGO_BASE, CPF, NUMERO_RG, NOME, 
  ENDERECO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, CEP, 
  TELEFONE, TELEFONE_CELULAR, EMAIL, 
  DATA_NASCIMENTO, NACIONALIDADE, SEXO, ESTADO_CIVIL, 
  PORTADOR_DEFICIENCIA, TIPO_CARGO, DATA_CADASTRO)
VALUES (
  TALENTOS_WEB_SEQ.NEXTVAL, CODIGO_BASE, CPF, NUMERO_RG, NOME, 
  ENDERECO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, CEP, 
  TELEFONE, TELEFONE_CELULAR, EMAIL, 
  DATA_NASCIMENTO, NACIONALIDADE, SEXO, ESTADO_CIVIL, 
  PORTADOR_DEFICIENCIA, TIPO_CARGO, DATA_CADASTRO)

SELECT NOME ||' - '||UF FROM MUNICIPIOS_WEB ORDER BY UF --WHERE NOME = 'LIMEIRA' 

DELETE FROM MUNICIPIOS_WEB WHERE UF = '  '

SELECT F.CHAVE, F.DESCRICAO, F.INSTITUICAO, F.CIDADE, F.DATA_INICIO, F.DATA_TERMINO, M.NOME NOME_CIDADE, M.UF
  FROM FORMACAO_WEB F, MUNICIPIOS_WEB M
 WHERE F.CIDADE = M.CHAVE
   AND F.CHAVE_USUARIO_WEB = 0
 
SELECT * FROM MUNICIPIOS_WEB WHERE NOME = 'LIMEIRA' 
 
SELECT F.CHAVE, F.DESCRICAO, F.INSTITUICAO, F.CIDADE, F.DATA_INICIO, F.DATA_TERMINO, M.NOME NOME_CIDADE, M.UF FROM FORMACAO_WEB F, MUNICIPIOS_WEB M WHERE F.CIDADE = M.CHAVE --AND F.CHAVE_USUARIO_WEB = 21 AND TIPO = 'C'
 
INSERT INTO FORMACAO_WEB (
  CHAVE, CHAVE_USUARIO_WEB, DESCRICAO, INSTITUICAO, CIDADE, DATA_INICIO, DATA_TERMINO, TIPO)
VALUES (
  FORMACAO_WEB_SEQ.NEXTVAL, CHAVE_USUARIO_WEB, DESCRICAO, INSTITUICAO, CIDADE, DATA_INICIO, DATA_TERMINO, TIPO)
  
SELECT * FROM FORMACAO_WEB

DELETE FROM FORMACAO_WEB --WHERE CHAVE = 1  

INSERT INTO EXPERIENCIA_WEB (
  CHAVE, CHAVE_USUARIO_WEB, EMPRESA, CIDADE, CARGO, DATA_INICIO, DATA_TERMINO, RESUMO)
VALUES (
  EXPERIENCIA_WEB_SEQ.NEXTVAL, CHAVE_USUARIO_WEB, EMPRESA, CIDADE, CARGO, DATA_INICIO, DATA_TERMINO, RESUMO)

SELECT E.CHAVE, E.CHAVE_USUARIO_WEB, E.EMPRESA, E.CIDADE, E.CARGO, E.DATA_INICIO, E.DATA_TERMINO, E.RESUMO, M.NOME NOME_CIDADE, M.UF  
  FROM EXPERIENCIA_WEB E, MUNICIPIOS_WEB M
 WHERE E.CIDADE = M.CHAVE
   AND CHAVE_USUARIO_WEB = 0
   
SELECT CPF, NUMERO_RG, NOME, ENDERECO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, CEP, 
       TELEFONE, TELEFONE_CELULAR, EMAIL, DATA_NASCIMENTO, NACIONALIDADE, SEXO, 
       ESTADO_CIVIL, PORTADOR_DEFICIENCIA, TIPO_CARGO, DATA_CADASTRO 
  FROM TALENTOS_WEB
 WHERE CHAVE_USUARIO_WEB = 21   
 
 
select * from experiencia_web

delete from experiencia_web 



SELECT * FROM USUARIOS_WEB

SELECT * FROM TALENTOS_WEB --WHERE CHAVE_USUARIO_WEB = 21