DROP TABLE FOLHA_WEB;

CREATE TABLE FOLHA_WEB
(
  CODIGO_BASE		NUMBER		     NOT NULL,
  ANO_MES          	VARCHAR2(6)          NOT NULL,
  ANO_MES_PAGTO    	VARCHAR2(6)          NOT NULL,
  FUNCIONARIO      	NUMBER               NOT NULL,
  TIPO_MOVTO       	VARCHAR2(10)         NOT NULL,
  COD_EVENTO	   	VARCHAR2(6)	     NOT NULL,		
  EVENTO           	VARCHAR2(50),
  TIPO_EVENTO      	VARCHAR2(10)         NOT NULL,
  REFERENCIA       	NUMBER(17,2),
  VALOR            	NUMBER(17,2),
  VALOR_CALCULADO  	NUMBER(17,2),
  REF_CALCULADO    	NUMBER(17,2),
  DATA_PAGTO	   	DATE			NOT NULL,
  SALARIO_BASE	   	NUMBER			NOT NULL,
  BASE_INSS		NUMBER			NOT NULL,
  BASE_FGTS		NUMBER			NOT NULL,
  FGTS_MES		NUMBER			NOT NULL,
  BASE_IRRF		NUMBER			NOT NULL
);

CREATE INDEX FW_CODIGO_BASE_I ON FOLHA_WEB (CODIGO_BASE);

CREATE INDEX FW_ANO_MES_I ON FOLHA_WEB (ANO_MES);

CREATE INDEX FW_FUNCIONARIO_I ON FOLHA_WEB (FUNCIONARIO);