DROP TABLE FOLHA_WEB;

CREATE TABLE FOLHA_WEB
(
  ANO_MES          VARCHAR2(6)             NOT NULL,
  ANO_MES_PAGTO    VARCHAR2(6)             NOT NULL,
  FUNCIONARIO      NUMBER                       NOT NULL,
  TIPO_MOVTO       VARCHAR2(10)            NOT NULL,
  EVENTO           VARCHAR2(50),
  TIPO_EVENTO      VARCHAR2(10)            NOT NULL,
  REFERENCIA       NUMBER(17,2),
  VALOR            NUMBER(17,2),
  VALOR_CALCULADO  NUMBER(17,2),
  REF_CALCULADO    NUMBER(17,2)
);

CREATE INDEX FW_ANO_MES_I ON FOLHA_WEB (ANO_MES);

CREATE INDEX FW_FUNCIONARIO_I ON FOLHA_WEB (FUNCIONARIO);