DROP TABLE PARAMS_WEB;

CREATE TABLE PARAMS_WEB (
  CODIGO_BASE			NUMBER,
  SMTP_REQAUT			VARCHAR2(3)	NULL,
  SMTP_SERVIDOR			VARCHAR2(100)	NULL,
  SMTP_PORTA			NUMBER		NULL,
  SMTP_USUARIO_FOLHA		VARCHAR2(50)	NULL,
  SMTP_SENHA_FOLHA		VARCHAR2(20)	NULL,
  LOGIN_SMTP_USUARIO_FOLHA	VARCHAR2(50)	NULL,
  LOGIN_SMTP_SENHA_FOLHA	VARCHAR2(20)	NULL);
  
  
INSERT INTO PARAMS_WEB (  
  SMTP_REQAUT, SMTP_SERVIDOR, SMTP_PORTA, SMTP_USUARIO_FOLHA, SMTP_SENHA_FOLHA, LOGIN_SMTP_USUARIO_FOLHA, LOGIN_SMTP_SENHA_FOLHA)
VALUES (
  NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  
COMMIT;